services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules
  backend:
    build: ./service
    ports:
      - "5000:5000"
    volumes:
      - ./service:/service
      - /service/node_modules